import './reset.css';
import './settings.css';
import './global.css';
import { ThemeLayout } from '#uikit/layouts/ThemeLayout/ThemeLayout';

export const metadata = {
  title: 'Welcome to my-site',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeLayout>{children}</ThemeLayout>
      </body>
    </html>
  );
}
