import './global.css';
import { MainLayout } from '#uikit/layouts/MainLayout/MainLayout';

export const metadata = {
  title: 'Welcome to my-site',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
